spring:
  application:
    name: mintos-accountsdata
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;
    #TRACE_LEVEL_FILE=4
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console    
  sql:
    init:
      mode: always


exchange:
  api:
    url: https://v6.exchangerate-api.com/v6
    key: 49a1430ad3321c9293879278

management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: ALWAYS

logging:
  level:
    io.github:
      resilience4j: DEBUG